version: '3'

services:
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super-secure-pw
      POSTGRES_DB: fullstack-task
    ports:
      - '3002:5432'